-- MySQL Script generated by MySQL Workbench
-- 12/10/16 12:57:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Mafia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Mafia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mafia` DEFAULT CHARACTER SET utf8 ;
USE `Mafia` ;

-- -----------------------------------------------------
-- Table `Mafia`.`Post_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mafia`.`Post_types` (
  `id` INT NOT NULL DEFAULT 1,
  `Post` VARCHAR(45) NULL,
  `Profit` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mafia`.`Business_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mafia`.`Business_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `profit` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mafia`.`District`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mafia`.`District` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mafia`.`Region_of_responsibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mafia`.`Region_of_responsibility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Business_id` INT NOT NULL,
  `District_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Business_id`, `District_id`),
  INDEX `fk_District_Business1_idx` (`Business_id` ASC),
  INDEX `fk_Region_of_responsibility_District1_idx` (`District_id` ASC),
  CONSTRAINT `fk_District_Business1`
    FOREIGN KEY (`Business_id`)
    REFERENCES `Mafia`.`Business_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Region_of_responsibility_District1`
    FOREIGN KEY (`District_id`)
    REFERENCES `Mafia`.`District` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mafia`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mafia`.`Person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Post_types_id` INT NOT NULL,
  `Person_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL,
  `gun` DECIMAL NULL,
  `Date of Birth` DATE NULL,
  `Region_of_responsibility_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Person_Person1_idx` (`Person_id` ASC),
  INDEX `fk_Person_Post_types1_idx` (`Post_types_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Person_Region_of_responsibility1_idx` (`Region_of_responsibility_id` ASC),
  CONSTRAINT `fk_Person_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `Mafia`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Post_types1`
    FOREIGN KEY (`Post_types_id`)
    REFERENCES `Mafia`.`Post_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Region_of_responsibility1`
    FOREIGN KEY (`Region_of_responsibility_id`)
    REFERENCES `Mafia`.`Region_of_responsibility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mafia`.`Mission_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mafia`.`Mission_types` (
  `id` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Region_of_responsibility_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Region_of_responsibility_id`),
  INDEX `fk_Mission_types_Region_of_responsibility1_idx` (`Region_of_responsibility_id` ASC),
  CONSTRAINT `fk_Mission_types_Region_of_responsibility1`
    FOREIGN KEY (`Region_of_responsibility_id`)
    REFERENCES `Mafia`.`Region_of_responsibility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mafia`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mafia`.`Tasks` (
  `id` INT NOT NULL,
  `Date` DATE NULL,
  `Profit` INT NULL,
  `Result` TINYINT(1) NULL,
  `Start_time` DATETIME NULL,
  `End_time` DATETIME NULL,
  `Real_end_time` DATETIME NULL,
  `Mission_types_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Mission_types_id`),
  INDEX `fk_Tasks_Mission_types1_idx` (`Mission_types_id` ASC),
  CONSTRAINT `fk_Tasks_Mission_types1`
    FOREIGN KEY (`Mission_types_id`)
    REFERENCES `Mafia`.`Mission_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mafia`.`Person_has_Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mafia`.`Person_has_Tasks` (
  `Person_id` INT NOT NULL,
  `Tasks_id` INT NOT NULL,
  PRIMARY KEY (`Person_id`, `Tasks_id`),
  INDEX `fk_Person_has_Tasks_Tasks1_idx` (`Tasks_id` ASC),
  INDEX `fk_Person_has_Tasks_Person1_idx` (`Person_id` ASC),
  CONSTRAINT `fk_Person_has_Tasks_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `Mafia`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_has_Tasks_Tasks1`
    FOREIGN KEY (`Tasks_id`)
    REFERENCES `Mafia`.`Tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
