# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'district',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MissionTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=45, null=True)),
            ],
            options={
                'db_table': 'mission_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('gun', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, db_column='Date of Birth', null=True)),
                ('personType', models.ForeignKey(blank=True, db_column='Person_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.Person')),
            ],
            options={
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonHasTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(db_column='Person_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.Person')),
            ],
            options={
                'db_table': 'person_has_tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post', models.CharField(blank=True, db_column='Post', max_length=45, null=True)),
                ('profit', models.IntegerField(blank=True, db_column='Profit', null=True)),
            ],
            options={
                'db_table': 'post_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegionOfResponsibility',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('business', models.ForeignKey(db_column='Business_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.BusinessType')),
                ('district', models.ForeignKey(db_column='District_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.District')),
            ],
            options={
                'db_table': 'region_of_responsibility',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('profit', models.IntegerField(blank=True, db_column='Profit', null=True)),
                ('result', models.IntegerField(blank=True, db_column='Result', null=True)),
                ('start_time', models.DateTimeField(blank=True, db_column='Start_time', null=True)),
                ('end_time', models.DateTimeField(blank=True, db_column='End_time', null=True)),
                ('real_end_time', models.DateTimeField(blank=True, db_column='Real_end_time', null=True)),
                ('mission_types', models.ForeignKey(db_column='Mission_types_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.MissionTypes')),
            ],
            options={
                'db_table': 'tasks',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='personhastasks',
            name='tasks',
            field=models.ForeignKey(db_column='Tasks_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.Tasks'),
        ),
        migrations.AddField(
            model_name='person',
            name='post_types',
            field=models.ForeignKey(db_column='Post_types_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.PostTypes'),
        ),
        migrations.AddField(
            model_name='person',
            name='region_of_responsibility',
            field=models.ForeignKey(blank=True, db_column='Region_of_responsibility_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mafia_tables.RegionOfResponsibility'),
        ),
        migrations.AddField(
            model_name='missiontypes',
            name='region_of_responsibility',
            field=models.ForeignKey(db_column='Region_of_responsibility_id', on_delete=django.db.models.deletion.DO_NOTHING, to='mafia_tables.RegionOfResponsibility'),
        ),
        migrations.AlterUniqueTogether(
            name='tasks',
            unique_together=set([('id', 'mission_types')]),
        ),
        migrations.AlterUniqueTogether(
            name='regionofresponsibility',
            unique_together=set([('id', 'business', 'district')]),
        ),
        migrations.AlterUniqueTogether(
            name='personhastasks',
            unique_together=set([('person', 'tasks')]),
        ),
        migrations.AlterUniqueTogether(
            name='missiontypes',
            unique_together=set([('id', 'region_of_responsibility')]),
        ),
    ]
