# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_tables', '0002_auto_20170120_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontypes',
            name='region_of_responsibility',
            field=models.ForeignKey(db_column='Region_of_responsibility_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.RegionOfResponsibility'),
        ),
        migrations.AlterField(
            model_name='person',
            name='region_of_responsibility',
            field=models.ForeignKey(blank=True, db_column='Region_of_responsibility_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.RegionOfResponsibility'),
        ),
    ]
