# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_tables', '0004_auto_20170120_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personhastasks',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='missiontypes',
            name='region_of_responsibility',
            field=models.ForeignKey(db_column='Region_of_responsibility_id', on_delete=django.db.models.deletion.DO_NOTHING, to='mafia_tables.RegionOfResponsibility'),
        ),
        migrations.AlterField(
            model_name='person',
            name='post_types',
            field=models.ForeignKey(db_column='Post_types_id', on_delete=django.db.models.deletion.DO_NOTHING, to='mafia_tables.PostTypes'),
        ),
        migrations.AlterField(
            model_name='person',
            name='region_of_responsibility',
            field=models.ForeignKey(blank=True, db_column='Region_of_responsibility_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mafia_tables.RegionOfResponsibility'),
        ),
        migrations.AlterField(
            model_name='regionofresponsibility',
            name='business',
            field=models.ForeignKey(db_column='Business_id', on_delete=django.db.models.deletion.DO_NOTHING, to='mafia_tables.BusinessType'),
        ),
        migrations.AlterField(
            model_name='regionofresponsibility',
            name='district',
            field=models.ForeignKey(db_column='District_id', on_delete=django.db.models.deletion.DO_NOTHING, to='mafia_tables.District'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='mission_types',
            field=models.ForeignKey(db_column='Mission_types_id', on_delete=django.db.models.deletion.DO_NOTHING, to='mafia_tables.MissionTypes'),
        ),
    ]
