# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_tables', '0006_auto_20170120_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personhastasks',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='personType',
            new_name='personToObey',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gun',
        ),
    ]
