# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_tables', '0007_auto_20170120_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='missiontypes',
            name='region_of_responsibility',
            field=models.ForeignKey(db_column='Region_of_responsibility_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.RegionOfResponsibility'),
        ),
        migrations.AlterField(
            model_name='person',
            name='post_types',
            field=models.ForeignKey(db_column='Post_types_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.PostTypes'),
        ),
        migrations.AlterField(
            model_name='person',
            name='region_of_responsibility',
            field=models.ForeignKey(blank=True, db_column='Region_of_responsibility_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.RegionOfResponsibility'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='mission_types',
            field=models.ForeignKey(db_column='Mission_types_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.MissionTypes'),
        ),
    ]
