# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_tables', '0008_auto_20170120_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionofresponsibility',
            name='business',
            field=models.ForeignKey(db_column='Business_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.BusinessType'),
        ),
        migrations.AlterField(
            model_name='regionofresponsibility',
            name='district',
            field=models.ForeignKey(db_column='District_id', on_delete=django.db.models.deletion.CASCADE, to='mafia_tables.District'),
        ),
    ]
